import Menu from '@/app/restaurant/[slug]/components/Menu';
import RestaurantNavBar from '@/app/restaurant/[slug]/components/RestaurantNavBar';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Menu - Milestones Grill (Toronto)',
  description: 'Generated by create next app',
};

export default function RestaurantMenu() {
  return (
    <div className="bg-white w-[100%] rounded p-3 shadow">
      <RestaurantNavBar />
      <Menu />
    </div>
  );
}
