import Description from '@/app/restaurant/[slug]/components/Description';
import Images from '@/app/restaurant/[slug]/components/Images';
import Rating from '@/app/restaurant/[slug]/components/Rating';
import ReservationCard from '@/app/restaurant/[slug]/components/ReservationCard';
import RestaurantNavBar from '@/app/restaurant/[slug]/components/RestaurantNavBar';
import Reviews from '@/app/restaurant/[slug]/components/Reviews';
import Title from '@/app/restaurant/[slug]/components/Title';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Milestones Grill (Toronto)',
  description: 'Generated by create next app',
};

export default function RestaurantDetails() {
  return (
    <>
      <div className="bg-white w-[70%] rounded p-3 shadow">
        <RestaurantNavBar />
        <Title />
        <Rating />
        <Description />
        <Images />
        <Reviews />
      </div>
      <div className="w-[27%] relative text-reg">
        <ReservationCard />
      </div>
    </>
  );
}
